workflows:
  workflow-name:
    environment:
      groups:
        - "firebase_credentials"
    scripts:
      - |
        set -e

        echo $ANDROID_FIREBASE_SECRET > $CM_BUILD_DIR/android/app/google-services.json
        echo $IOS_FIREBASE_SECRET > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
